// <auto-generated />
using System;
using DBU_LibrarySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBU_LibrarySystem.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260425065420_AddDepartmentOnly")]
    partial class AddDepartmentOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBU_LibrarySystem.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfPublication")
                        .HasColumnType("int");

                    b.HasKey("ISBN");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = "978-0131103627",
                            Author = "Brian W. Kernighan",
                            Category = "Programming",
                            Title = "The C Programming Language",
                            YearOfPublication = 1988
                        },
                        new
                        {
                            ISBN = "978-0201616224",
                            Author = "Andy Hunt",
                            Category = "Software Engineering",
                            Title = "The Pragmatic Programmer",
                            YearOfPublication = 1999
                        },
                        new
                        {
                            ISBN = "978-0132350884",
                            Author = "Robert C. Martin",
                            Category = "Programming",
                            Title = "Clean Code",
                            YearOfPublication = 2008
                        },
                        new
                        {
                            ISBN = "978-0596007126",
                            Author = "Eric Freeman",
                            Category = "Design",
                            Title = "Head First Design Patterns",
                            YearOfPublication = 2004
                        },
                        new
                        {
                            ISBN = "978-0262033848",
                            Author = "Thomas H. Cormen",
                            Category = "Computer Science",
                            Title = "Introduction to Algorithms",
                            YearOfPublication = 2009
                        },
                        new
                        {
                            ISBN = "978-0321125217",
                            Author = "Martin Fowler",
                            Category = "Software Engineering",
                            Title = "Refactoring",
                            YearOfPublication = 1999
                        });
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.BookCopy", b =>
                {
                    b.Property<string>("CopyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CopyId");

                    b.HasIndex("ISBN");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            CopyId = "1001-C1",
                            ISBN = "978-0131103627",
                            Status = "Available"
                        },
                        new
                        {
                            CopyId = "1002-C1",
                            ISBN = "978-0201616224",
                            Status = "Borrowed"
                        },
                        new
                        {
                            CopyId = "1003-C1",
                            ISBN = "978-0132350884",
                            Status = "Borrowed"
                        },
                        new
                        {
                            CopyId = "1004-C1",
                            ISBN = "978-0596007126",
                            Status = "Borrowed"
                        },
                        new
                        {
                            CopyId = "1005-C1",
                            ISBN = "978-0262033848",
                            Status = "Available"
                        },
                        new
                        {
                            CopyId = "1006-C1",
                            ISBN = "978-0321125217",
                            Status = "Reserved"
                        });
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CopyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CopyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CopyId = "1006-C1",
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UserId = "std2"
                        });
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CopyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsFinePaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CopyId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CopyId = "1003-C1",
                            DueDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            IsFinePaid = false,
                            Status = "Active",
                            UserId = "std1"
                        },
                        new
                        {
                            Id = 2,
                            BorrowDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CopyId = "1005-C1",
                            DueDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            IsFinePaid = false,
                            ReturnDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = "std2"
                        },
                        new
                        {
                            Id = 3,
                            BorrowDate = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CopyId = "1002-C1",
                            DueDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            IsFinePaid = false,
                            Status = "Active",
                            UserId = "std2"
                        },
                        new
                        {
                            Id = 4,
                            BorrowDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CopyId = "1004-C1",
                            DueDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m,
                            IsFinePaid = false,
                            Status = "Active",
                            UserId = "std2"
                        });
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCardImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "admin",
                            IsApproved = true,
                            Name = "System Admin",
                            Password = "admin",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = "lib",
                            IsApproved = true,
                            Name = "Main Librarian",
                            Password = "lib",
                            Role = "Librarian"
                        },
                        new
                        {
                            UserId = "std1",
                            IsApproved = true,
                            Name = "Alice Student",
                            Password = "student",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = "std2",
                            IsApproved = true,
                            Name = "Bob Smith",
                            Password = "password123",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = "std3",
                            IsApproved = false,
                            Name = "Charlie Davis",
                            Password = "password123",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = "staff1",
                            IsApproved = true,
                            Name = "John Staff",
                            Password = "staff",
                            Role = "Librarian"
                        });
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.BookCopy", b =>
                {
                    b.HasOne("DBU_LibrarySystem.Models.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Notification", b =>
                {
                    b.HasOne("DBU_LibrarySystem.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Reservation", b =>
                {
                    b.HasOne("DBU_LibrarySystem.Models.BookCopy", "BookCopy")
                        .WithMany()
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBU_LibrarySystem.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Transaction", b =>
                {
                    b.HasOne("DBU_LibrarySystem.Models.BookCopy", "BookCopy")
                        .WithMany()
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBU_LibrarySystem.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("DBU_LibrarySystem.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Reservations");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
